export interface ComponentItem {
  id: string;
  name: string;
  description: string;
  icon: string;
  status: 'pending' | 'ready';
  dependencies: string[];
  filePath: string;
}

export interface ComponentCategory {
  id: string;
  name: string;
  icon: string;
  description: string;
  components: ComponentItem[];
}

export const componentCategories: ComponentCategory[] = [
  // ──────────────────────────────────────────────
  // 1. NAVIGATION & LAYOUT
  // ──────────────────────────────────────────────
  {
    id: 'navigation',
    name: 'Navigation & Layout',
    icon: '🧭',
    description: 'Structural components for page navigation, headers, footers, and layout management.',
    components: [
      {
        id: 'navbar',
        name: 'Navbar',
        description: 'Top navigation bar with logo, links, search, user menu, and mobile hamburger.',
        icon: '🔝',
        status: 'pending',
        dependencies: ['Button', 'Avatar', 'Dropdown'],
        filePath: 'components/layout/Navbar.tsx',
      },
      {
        id: 'footer',
        name: 'Footer',
        description: 'Site footer with columns, links, social icons, newsletter signup, and copyright.',
        icon: '🔻',
        status: 'pending',
        dependencies: ['Input', 'Button'],
        filePath: 'components/layout/Footer.tsx',
      },
      {
        id: 'sidebar',
        name: 'Sidebar',
        description: 'Collapsible side navigation for dashboards and settings pages.',
        icon: '📋',
        status: 'pending',
        dependencies: ['Tooltip'],
        filePath: 'components/layout/Sidebar.tsx',
      },
      {
        id: 'bottom-nav',
        name: 'BottomNav',
        description: 'Mobile bottom navigation bar with icon tabs and active indicators.',
        icon: '📱',
        status: 'pending',
        dependencies: ['Badge'],
        filePath: 'components/layout/BottomNav.tsx',
      },
      {
        id: 'breadcrumb',
        name: 'Breadcrumb',
        description: 'Hierarchical page navigation trail with separators and icons.',
        icon: '🔗',
        status: 'pending',
        dependencies: [],
        filePath: 'components/layout/Breadcrumb.tsx',
      },
      {
        id: 'page-header',
        name: 'PageHeader',
        description: 'Page title area with title, subtitle, breadcrumbs, and action buttons.',
        icon: '📰',
        status: 'pending',
        dependencies: ['Button', 'Breadcrumb'],
        filePath: 'components/layout/PageHeader.tsx',
      },
      {
        id: 'tabs',
        name: 'Tabs',
        description: 'Tabbed navigation for switching between views. Supports icons and badges.',
        icon: '📑',
        status: 'pending',
        dependencies: [],
        filePath: 'components/layout/Tabs.tsx',
      },
      {
        id: 'pagination',
        name: 'Pagination',
        description: 'Page navigation with page numbers, prev/next, and page size selector.',
        icon: '📄',
        status: 'pending',
        dependencies: ['Button'],
        filePath: 'components/layout/Pagination.tsx',
      },
      {
        id: 'mobile-drawer',
        name: 'MobileDrawer',
        description: 'Slide-in drawer for mobile navigation and filters.',
        icon: '🔲',
        status: 'pending',
        dependencies: [],
        filePath: 'components/layout/MobileDrawer.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 2. FORMS & INPUTS
  // ──────────────────────────────────────────────
  {
    id: 'forms',
    name: 'Forms & Inputs',
    icon: '📝',
    description: 'Form controls for user input including text fields, selects, checkboxes, and file uploads.',
    components: [
      {
        id: 'input',
        name: 'Input',
        description: 'Text input with label, placeholder, helper text, error state, and icon support.',
        icon: '⌨️',
        status: 'ready',
        dependencies: [],
        filePath: 'components/Input.tsx',
      },
      {
        id: 'textarea',
        name: 'Textarea',
        description: 'Multi-line text input with auto-resize and character count.',
        icon: '📜',
        status: 'ready',
        dependencies: [],
        filePath: 'components/Textarea.tsx',
      },
      {
        id: 'select',
        name: 'Select',
        description: 'Dropdown select with search, multi-select, options groups, and custom rendering.',
        icon: '🔽',
        status: 'ready',
        dependencies: [],
        filePath: 'components/SelectSearch.tsx',
      },
      {
        id: 'form-select',
        name: 'FormSelect',
        description: 'Form-ready dropdown with label, validation, helper text, error state, and sizes.',
        icon: '📋',
        status: 'ready',
        dependencies: [],
        filePath: 'components/FormSelect.tsx',
      },
      {
        id: 'checkbox',
        name: 'Checkbox',
        description: 'Checkbox input with label, indeterminate state, and group support.',
        icon: '☑️',
        status: 'ready',
        dependencies: [],
        filePath: 'components/Checkbox.tsx',
      },
      {
        id: 'radio',
        name: 'Radio',
        description: 'Radio button group with labels and descriptions.',
        icon: '🔘',
        status: 'ready',
        dependencies: [],
        filePath: 'components/Radio.tsx',
      },
      {
        id: 'switch',
        name: 'Switch',
        description: 'Toggle switch for boolean settings with labels.',
        icon: '🎚️',
        status: 'ready',
        dependencies: [],
        filePath: 'components/Switch.tsx',
      },
      {
        id: 'form-field',
        name: 'FormField',
        description: 'Wrapper component providing label, helper text, error, and required indicator.',
        icon: '📦',
        status: 'ready',
        dependencies: [],
        filePath: 'components/FormSelect.tsx',
      },
      {
        id: 'search-bar',
        name: 'SearchBar',
        description: 'Search input with icon, clear button, suggestions, and recent searches.',
        icon: '🔍',
        status: 'ready',
        dependencies: [],
        filePath: 'components/SearchBar.tsx',
      },
      {
        id: 'file-upload',
        name: 'FileUpload',
        description: 'Drag-and-drop file upload with preview, progress, and validation.',
        icon: '📤',
        status: 'ready',
        dependencies: [],
        filePath: 'components/FileUpload.tsx',
      },
      {
        id: 'date-picker',
        name: 'DatePicker',
        description: 'Calendar date picker with range selection and format options.',
        icon: '📅',
        status: 'ready',
        dependencies: [],
        filePath: 'components/DatePicker.tsx',
      },
      {
        id: 'autocomplete',
        name: 'Autocomplete',
        description: 'Search input with dropdown suggestions, categories, and recent items.',
        icon: '💡',
        status: 'ready',
        dependencies: [],
        filePath: 'components/Autocomplete.tsx',
      },
      {
        id: 'slider',
        name: 'Slider',
        description: 'Range slider for numeric values with marks and tooltips.',
        icon: '🎚️',
        status: 'ready',
        dependencies: [],
        filePath: 'components/Slider.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 3. DATA DISPLAY
  // ──────────────────────────────────────────────
  {
    id: 'data-display',
    name: 'Data Display',
    icon: '📊',
    description: 'Components for displaying structured data, lists, cards, badges, and visual content.',
    components: [
      {
        id: 'table',
        name: 'Table',
        description: 'Data table with sorting, selection, sticky headers, and responsive modes.',
        icon: '📋',
        status: 'pending',
        dependencies: ['Checkbox', 'Pagination'],
        filePath: 'components/data/Table.tsx',
      },
      {
        id: 'data-grid',
        name: 'DataGrid',
        description: 'Advanced data grid with column resizing, filtering, virtual scrolling.',
        icon: '🔲',
        status: 'pending',
        dependencies: ['Table', 'Input', 'Select'],
        filePath: 'components/data/DataGrid.tsx',
      },
      {
        id: 'list',
        name: 'List',
        description: 'List component with items, dividers, sections, and actions.',
        icon: '📃',
        status: 'pending',
        dependencies: ['Avatar', 'Badge'],
        filePath: 'components/data/List.tsx',
      },
      {
        id: 'card',
        name: 'Card',
        description: 'Generic card container with header, body, footer, and media areas.',
        icon: '🃏',
        status: 'pending',
        dependencies: [],
        filePath: 'components/data/Card.tsx',
      },
      {
        id: 'stat-card',
        name: 'StatCard',
        description: 'Statistics card showing metric with value, label, trend, and icon.',
        icon: '📈',
        status: 'pending',
        dependencies: ['Card'],
        filePath: 'components/data/StatCard.tsx',
      },
      {
        id: 'badge',
        name: 'Badge',
        description: 'Small status indicator with color variants and dot mode.',
        icon: '🏷️',
        status: 'pending',
        dependencies: [],
        filePath: 'components/data/Badge.tsx',
      },
      {
        id: 'tag',
        name: 'Tag',
        description: 'Removable tag chip with icon and color options.',
        icon: '🏷️',
        status: 'pending',
        dependencies: [],
        filePath: 'components/data/Tag.tsx',
      },
      {
        id: 'avatar',
        name: 'Avatar',
        description: 'User avatar with image, initials fallback, size variants, and online indicator.',
        icon: '👤',
        status: 'pending',
        dependencies: [],
        filePath: 'components/data/Avatar.tsx',
      },
      {
        id: 'avatar-group',
        name: 'AvatarGroup',
        description: 'Stacked avatar group with overflow count.',
        icon: '👥',
        status: 'pending',
        dependencies: ['Avatar'],
        filePath: 'components/data/AvatarGroup.tsx',
      },
      {
        id: 'timeline',
        name: 'Timeline',
        description: 'Vertical timeline for events, history, and activity logs.',
        icon: '📅',
        status: 'pending',
        dependencies: ['Avatar'],
        filePath: 'components/data/Timeline.tsx',
      },
      {
        id: 'empty-state',
        name: 'EmptyState',
        description: 'Placeholder for empty content with icon, message, and action button.',
        icon: '📭',
        status: 'pending',
        dependencies: ['Button'],
        filePath: 'components/data/EmptyState.tsx',
      },
      {
        id: 'stat-grid',
        name: 'StatGrid',
        description: 'Grid layout for multiple StatCards on dashboards.',
        icon: '📊',
        status: 'pending',
        dependencies: ['StatCard'],
        filePath: 'components/data/StatGrid.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 4. FEEDBACK & OVERLAYS
  // ──────────────────────────────────────────────
  {
    id: 'feedback',
    name: 'Feedback & Overlays',
    icon: '🔔',
    description: 'User feedback components including alerts, toasts, modals, tooltips, and loading states.',
    components: [
      {
        id: 'alert',
        name: 'Alert',
        description: 'Inline alert banner with info, success, warning, and error variants.',
        icon: '⚠️',
        status: 'pending',
        dependencies: [],
        filePath: 'components/feedback/Alert.tsx',
      },
      {
        id: 'toast',
        name: 'Toast',
        description: 'Floating notification toast with auto-dismiss and action buttons.',
        icon: '🍞',
        status: 'pending',
        dependencies: ['Button'],
        filePath: 'components/feedback/Toast.tsx',
      },
      {
        id: 'progress',
        name: 'Progress',
        description: 'Progress bar and circular progress indicator.',
        icon: '📊',
        status: 'pending',
        dependencies: [],
        filePath: 'components/feedback/Progress.tsx',
      },
      {
        id: 'spinner',
        name: 'Spinner',
        description: 'Loading spinner with size variants and overlay mode.',
        icon: '🔄',
        status: 'pending',
        dependencies: [],
        filePath: 'components/feedback/Spinner.tsx',
      },
      {
        id: 'skeleton',
        name: 'Skeleton',
        description: 'Content placeholder loading skeleton with shimmer animation.',
        icon: '💀',
        status: 'pending',
        dependencies: [],
        filePath: 'components/feedback/Skeleton.tsx',
      },
      {
        id: 'tooltip',
        name: 'Tooltip',
        description: 'Hover tooltip with positioning and delay.',
        icon: '💬',
        status: 'pending',
        dependencies: [],
        filePath: 'components/feedback/Tooltip.tsx',
      },
      {
        id: 'popover',
        name: 'Popover',
        description: 'Click-triggered floating panel with rich content.',
        icon: '🫧',
        status: 'pending',
        dependencies: [],
        filePath: 'components/feedback/Popover.tsx',
      },
      {
        id: 'modal',
        name: 'Modal',
        description: 'Dialog modal with header, body, footer, and backdrop.',
        icon: '🪟',
        status: 'pending',
        dependencies: ['Button'],
        filePath: 'components/feedback/Modal.tsx',
      },
      {
        id: 'confirm-dialog',
        name: 'ConfirmDialog',
        description: 'Confirmation dialog for destructive actions.',
        icon: '❓',
        status: 'pending',
        dependencies: ['Modal', 'Button'],
        filePath: 'components/feedback/ConfirmDialog.tsx',
      },
      {
        id: 'sheet',
        name: 'Sheet',
        description: 'Slide-in panel from edge for forms and details.',
        icon: '📄',
        status: 'pending',
        dependencies: [],
        filePath: 'components/feedback/Sheet.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 5. ACTIONS & BUTTONS
  // ──────────────────────────────────────────────
  {
    id: 'actions',
    name: 'Actions & Buttons',
    icon: '⚡',
    description: 'Action-triggering components like dropdowns, button groups, and floating action buttons.',
    components: [
      {
        id: 'button',
        name: 'Button',
        description: 'Base button with variants, sizes, loading state, icons, and full-width support.',
        icon: '🔘',
        status: 'ready',
        dependencies: [],
        filePath: 'components/Button.tsx',
      },
      {
        id: 'dropdown',
        name: 'Dropdown',
        description: 'Dropdown menu with items, separators, icons, keyboard navigation.',
        icon: '📋',
        status: 'ready',
        dependencies: [],
        filePath: 'components/Dropdown.tsx',
      },
      {
        id: 'button-group',
        name: 'ButtonGroup',
        description: 'Grouped buttons with shared borders and active states.',
        icon: '🔘',
        status: 'ready',
        dependencies: ['Button'],
        filePath: 'components/ButtonGroup.tsx',
      },
      {
        id: 'icon-button',
        name: 'IconButton',
        description: 'Button with only an icon, with tooltip support.',
        icon: '🎯',
        status: 'ready',
        dependencies: [],
        filePath: 'components/IconButton.tsx',
      },
      {
        id: 'fab',
        name: 'FloatingActionButton',
        description: 'Floating action button for primary screen actions.',
        icon: '➕',
        status: 'ready',
        dependencies: [],
        filePath: 'components/FAB.tsx',
      },
      {
        id: 'context-menu',
        name: 'ContextMenu',
        description: 'Right-click context menu with actions.',
        icon: '🖱️',
        status: 'ready',
        dependencies: [],
        filePath: 'components/ContextMenu.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 6. JOB-SPECIFIC
  // ──────────────────────────────────────────────
  {
    id: 'jobs',
    name: 'Job & Career',
    icon: '💼',
    description: 'Domain-specific components for job listings, applications, matching, and career features.',
    components: [
      {
        id: 'job-card',
        name: 'JobCard',
        description: 'Job listing card with title, company, salary, location, match score, and save button.',
        icon: '💼',
        status: 'pending',
        dependencies: ['Card', 'Badge', 'Avatar'],
        filePath: 'components/jobs/JobCard.tsx',
      },
      {
        id: 'job-filter',
        name: 'JobFilter',
        description: 'Job search filters panel with location, salary, experience, job type, and more.',
        icon: '🎛️',
        status: 'pending',
        dependencies: ['Select', 'Slider', 'Checkbox', 'Input'],
        filePath: 'components/jobs/JobFilter.tsx',
      },
      {
        id: 'job-detail',
        name: 'JobDetail',
        description: 'Full job detail view with description, requirements, benefits, and apply button.',
        icon: '📋',
        status: 'pending',
        dependencies: ['Card', 'Badge', 'Button', 'Avatar'],
        filePath: 'components/jobs/JobDetail.tsx',
      },
      {
        id: 'application-card',
        name: 'ApplicationCard',
        description: 'Job application status card with timeline, documents, and actions.',
        icon: '📨',
        status: 'pending',
        dependencies: ['Card', 'Badge', 'Timeline'],
        filePath: 'components/jobs/ApplicationCard.tsx',
      },
      {
        id: 'company-card',
        name: 'CompanyCard',
        description: 'Company profile card with logo, name, industry, size, and open positions.',
        icon: '🏢',
        status: 'pending',
        dependencies: ['Card', 'Badge'],
        filePath: 'components/jobs/CompanyCard.tsx',
      },
      {
        id: 'match-score',
        name: 'MatchScore',
        description: 'Visual match score indicator with percentage, breakdown, and ring chart.',
        icon: '🎯',
        status: 'pending',
        dependencies: ['Badge'],
        filePath: 'components/jobs/MatchScore.tsx',
      },
      {
        id: 'skill-badge',
        name: 'SkillBadge',
        description: 'Skill tag with proficiency level and verified indicator.',
        icon: '🛠️',
        status: 'pending',
        dependencies: ['Badge'],
        filePath: 'components/jobs/SkillBadge.tsx',
      },
      {
        id: 'salary-range',
        name: 'SalaryRange',
        description: 'Salary range display with market comparison and currency formatting.',
        icon: '💰',
        status: 'pending',
        dependencies: [],
        filePath: 'components/jobs/SalaryRange.tsx',
      },
      {
        id: 'eligibility-badge',
        name: 'EligibilityBadge',
        description: 'Shows candidate eligibility status for a job (eligible/not eligible).',
        icon: '✅',
        status: 'pending',
        dependencies: ['Badge'],
        filePath: 'components/jobs/EligibilityBadge.tsx',
      },
      {
        id: 'interview-card',
        name: 'InterviewCard',
        description: 'Interview schedule card with date, time, type, and meeting link.',
        icon: '🎥',
        status: 'pending',
        dependencies: ['Card', 'Badge', 'Button'],
        filePath: 'components/jobs/InterviewCard.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 7. USER & AUTH
  // ──────────────────────────────────────────────
  {
    id: 'auth',
    name: 'User & Authentication',
    icon: '🔐',
    description: 'Authentication forms, user profiles, and account management components.',
    components: [
      {
        id: 'login-form',
        name: 'LoginForm',
        description: 'Login form with email/phone, password, social logins, and forgot password.',
        icon: '🔑',
        status: 'pending',
        dependencies: ['Input', 'Button', 'Checkbox'],
        filePath: 'components/auth/LoginForm.tsx',
      },
      {
        id: 'signup-form',
        name: 'SignupForm',
        description: 'Registration form with role selection, OTP verification, and terms.',
        icon: '📝',
        status: 'pending',
        dependencies: ['Input', 'Button', 'Select'],
        filePath: 'components/auth/SignupForm.tsx',
      },
      {
        id: 'profile-card',
        name: 'ProfileCard',
        description: 'User profile summary with avatar, name, title, skills, and stats.',
        icon: '👤',
        status: 'pending',
        dependencies: ['Avatar', 'Badge', 'Card'],
        filePath: 'components/auth/ProfileCard.tsx',
      },
      {
        id: 'user-menu',
        name: 'UserMenu',
        description: 'Logged-in user dropdown menu with profile, settings, and logout.',
        icon: '🔽',
        status: 'pending',
        dependencies: ['Avatar', 'Dropdown'],
        filePath: 'components/auth/UserMenu.tsx',
      },
      {
        id: 'verification-badge',
        name: 'VerificationBadge',
        description: 'Profile verification indicators for phone, email, identity, education.',
        icon: '✅',
        status: 'pending',
        dependencies: ['Tooltip'],
        filePath: 'components/auth/VerificationBadge.tsx',
      },
      {
        id: 'otp-input',
        name: 'OTPInput',
        description: 'One-time password input with auto-focus and paste support.',
        icon: '🔢',
        status: 'pending',
        dependencies: ['Input'],
        filePath: 'components/auth/OTPInput.tsx',
      },
      {
        id: 'social-login',
        name: 'SocialLogin',
        description: 'Social login buttons for Google, Facebook, LinkedIn.',
        icon: '🌐',
        status: 'pending',
        dependencies: ['Button'],
        filePath: 'components/auth/SocialLogin.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 8. AI & CHAT
  // ──────────────────────────────────────────────
  {
    id: 'ai-chat',
    name: 'AI & Chat',
    icon: '🤖',
    description: 'AI assistant, chat interface, and conversational UI components.',
    components: [
      {
        id: 'chat-bubble',
        name: 'ChatBubble',
        description: 'Chat message bubble for user and AI messages with timestamps.',
        icon: '💬',
        status: 'pending',
        dependencies: ['Avatar'],
        filePath: 'components/ai/ChatBubble.tsx',
      },
      {
        id: 'chat-input',
        name: 'ChatInput',
        description: 'Chat message input with send button, attachment, and voice.',
        icon: '⌨️',
        status: 'pending',
        dependencies: ['Button'],
        filePath: 'components/ai/ChatInput.tsx',
      },
      {
        id: 'suggestion-chip',
        name: 'SuggestionChip',
        description: 'Clickable suggestion pills for AI quick actions.',
        icon: '💊',
        status: 'pending',
        dependencies: [],
        filePath: 'components/ai/SuggestionChip.tsx',
      },
      {
        id: 'typing-indicator',
        name: 'TypingIndicator',
        description: 'Animated typing indicator for AI responses.',
        icon: '⏳',
        status: 'pending',
        dependencies: [],
        filePath: 'components/ai/TypingIndicator.tsx',
      },
      {
        id: 'ai-score-ring',
        name: 'AIScoreRing',
        description: 'Circular score visualization for AI match/assessment scores.',
        icon: '🔵',
        status: 'pending',
        dependencies: [],
        filePath: 'components/ai/AIScoreRing.tsx',
      },
      {
        id: 'ai-explanation',
        name: 'AIExplanation',
        description: 'Expandable AI explanation card with reasoning breakdown.',
        icon: '💡',
        status: 'pending',
        dependencies: ['Card'],
        filePath: 'components/ai/AIExplanation.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 9. LEARNING & ASSESSMENT
  // ──────────────────────────────────────────────
  {
    id: 'learning',
    name: 'Learning & Assessment',
    icon: '📚',
    description: 'Components for courses, certifications, mock tests, and skill assessments.',
    components: [
      {
        id: 'course-card',
        name: 'CourseCard',
        description: 'Course listing card with thumbnail, title, instructor, rating, and progress.',
        icon: '📖',
        status: 'pending',
        dependencies: ['Card', 'Badge', 'Avatar'],
        filePath: 'components/learning/CourseCard.tsx',
      },
      {
        id: 'course-progress',
        name: 'CourseProgress',
        description: 'Course progress bar with module completion checklist.',
        icon: '📊',
        status: 'pending',
        dependencies: ['Progress'],
        filePath: 'components/learning/CourseProgress.tsx',
      },
      {
        id: 'quiz-card',
        name: 'QuizCard',
        description: 'Quiz question card with options, timer, and progress.',
        icon: '❓',
        status: 'pending',
        dependencies: ['Card', 'Radio', 'Progress'],
        filePath: 'components/learning/QuizCard.tsx',
      },
      {
        id: 'certification-badge',
        name: 'CertificationBadge',
        description: 'Earned certification badge with details and verify link.',
        icon: '🏆',
        status: 'pending',
        dependencies: ['Badge'],
        filePath: 'components/learning/CertificationBadge.tsx',
      },
      {
        id: 'skill-gap-chart',
        name: 'SkillGapChart',
        description: 'Visual chart comparing current skills vs target role requirements.',
        icon: '📉',
        status: 'pending',
        dependencies: ['Card'],
        filePath: 'components/learning/SkillGapChart.tsx',
      },
      {
        id: 'career-path',
        name: 'CareerPath',
        description: 'Step-by-step career roadmap with milestones and current position.',
        icon: '🗺️',
        status: 'pending',
        dependencies: ['Timeline', 'Badge'],
        filePath: 'components/learning/CareerPath.tsx',
      },
      {
        id: 'mock-test-card',
        name: 'MockTestCard',
        description: 'Mock test card with category, difficulty, duration, and attempts.',
        icon: '📝',
        status: 'pending',
        dependencies: ['Card', 'Badge'],
        filePath: 'components/learning/MockTestCard.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 10. MEDIA & CONTENT
  // ──────────────────────────────────────────────
  {
    id: 'media',
    name: 'Media & Content',
    icon: '🖼️',
    description: 'Media components for images, videos, files, icons, and rich content.',
    components: [
      {
        id: 'image',
        name: 'Image',
        description: 'Optimized image with lazy loading, fallback, and aspect ratio.',
        icon: '🖼️',
        status: 'pending',
        dependencies: [],
        filePath: 'components/media/Image.tsx',
      },
      {
        id: 'image-gallery',
        name: 'ImageGallery',
        description: 'Image gallery with lightbox, thumbnails, and navigation.',
        icon: '🖼️',
        status: 'pending',
        dependencies: ['Image'],
        filePath: 'components/media/ImageGallery.tsx',
      },
      {
        id: 'video-player',
        name: 'VideoPlayer',
        description: 'Video player with controls, fullscreen, and quality selection.',
        icon: '🎬',
        status: 'pending',
        dependencies: [],
        filePath: 'components/media/VideoPlayer.tsx',
      },
      {
        id: 'file-card',
        name: 'FileCard',
        description: 'File attachment card with icon, name, size, and download action.',
        icon: '📎',
        status: 'pending',
        dependencies: ['Button'],
        filePath: 'components/media/FileCard.tsx',
      },
      {
        id: 'icon',
        name: 'Icon',
        description: 'Icon wrapper component for consistent icon sizing and styling.',
        icon: '✨',
        status: 'pending',
        dependencies: [],
        filePath: 'components/media/Icon.tsx',
      },
      {
        id: 'rich-text',
        name: 'RichText',
        description: 'Rich text renderer for HTML/markdown content.',
        icon: '📝',
        status: 'pending',
        dependencies: [],
        filePath: 'components/media/RichText.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 11. MAPS & LOCATION
  // ──────────────────────────────────────────────
  {
    id: 'maps',
    name: 'Maps & Location',
    icon: '🗺️',
    description: 'Geolocation, map display, and distance calculation components.',
    components: [
      {
        id: 'map-view',
        name: 'MapView',
        description: 'Interactive map with markers, popups, and area highlighting.',
        icon: '🗺️',
        status: 'pending',
        dependencies: [],
        filePath: 'components/maps/MapView.tsx',
      },
      {
        id: 'location-picker',
        name: 'LocationPicker',
        description: 'Location selection with search, map click, and current location.',
        icon: '📍',
        status: 'pending',
        dependencies: ['Input', 'MapView'],
        filePath: 'components/maps/LocationPicker.tsx',
      },
      {
        id: 'distance-badge',
        name: 'DistanceBadge',
        description: 'Distance display from user to job location.',
        icon: '📏',
        status: 'pending',
        dependencies: ['Badge'],
        filePath: 'components/maps/DistanceBadge.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 12. PAYMENT
  // ──────────────────────────────────────────────
  {
    id: 'payment',
    name: 'Payment & Billing',
    icon: '💳',
    description: 'Payment method display, subscription plans, and transaction components.',
    components: [
      {
        id: 'payment-method',
        name: 'PaymentMethod',
        description: 'Payment method card with logo, last digits, and expiry.',
        icon: '💳',
        status: 'pending',
        dependencies: ['Card'],
        filePath: 'components/payment/PaymentMethod.tsx',
      },
      {
        id: 'pricing-card',
        name: 'PricingCard',
        description: 'Pricing tier card with features list, price, and CTA.',
        icon: '💲',
        status: 'pending',
        dependencies: ['Card', 'Button', 'Badge'],
        filePath: 'components/payment/PricingCard.tsx',
      },
      {
        id: 'transaction-item',
        name: 'TransactionItem',
        description: 'Transaction history item with status, amount, and date.',
        icon: '🧾',
        status: 'pending',
        dependencies: ['Badge'],
        filePath: 'components/payment/TransactionItem.tsx',
      },
      {
        id: 'premium-badge',
        name: 'PremiumBadge',
        description: 'Premium/Pro badge indicator for premium features.',
        icon: '⭐',
        status: 'pending',
        dependencies: ['Badge'],
        filePath: 'components/payment/PremiumBadge.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 13. DASHBOARD
  // ──────────────────────────────────────────────
  {
    id: 'dashboard',
    name: 'Dashboard',
    icon: '📊',
    description: 'Dashboard-specific components for analytics, notifications, and activity feeds.',
    components: [
      {
        id: 'notification-bell',
        name: 'NotificationBell',
        description: 'Notification bell icon with unread count and dropdown panel.',
        icon: '🔔',
        status: 'pending',
        dependencies: ['Badge', 'Dropdown'],
        filePath: 'components/dashboard/NotificationBell.tsx',
      },
      {
        id: 'activity-feed',
        name: 'ActivityFeed',
        description: 'Recent activity feed with icons, messages, and timestamps.',
        icon: '📰',
        status: 'pending',
        dependencies: ['Avatar', 'Timeline'],
        filePath: 'components/dashboard/ActivityFeed.tsx',
      },
      {
        id: 'chart-card',
        name: 'ChartCard',
        description: 'Card wrapper for charts with title, legend, and time range selector.',
        icon: '📈',
        status: 'pending',
        dependencies: ['Card', 'Select'],
        filePath: 'components/dashboard/ChartCard.tsx',
      },
      {
        id: 'quick-actions',
        name: 'QuickActions',
        description: 'Grid of quick action buttons for dashboard shortcuts.',
        icon: '⚡',
        status: 'pending',
        dependencies: ['Button'],
        filePath: 'components/dashboard/QuickActions.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 14. EMPLOYER / RECRUITMENT
  // ──────────────────────────────────────────────
  {
    id: 'employer',
    name: 'Employer & Recruitment',
    icon: '🏢',
    description: 'Employer-specific components for recruitment pipeline, candidate management, and hiring.',
    components: [
      {
        id: 'pipeline-board',
        name: 'PipelineBoard',
        description: 'Kanban-style recruitment pipeline (New → Screening → Interview → Offer → Hired).',
        icon: '📋',
        status: 'pending',
        dependencies: ['Card', 'Badge', 'Avatar'],
        filePath: 'components/employer/PipelineBoard.tsx',
      },
      {
        id: 'candidate-card',
        name: 'CandidateCard',
        description: 'Candidate summary card with name, skills, match score, and quick actions.',
        icon: '👤',
        status: 'pending',
        dependencies: ['Card', 'Avatar', 'Badge', 'MatchScore'],
        filePath: 'components/employer/CandidateCard.tsx',
      },
      {
        id: 'invitation-card',
        name: 'InvitationCard',
        description: 'Employer-to-candidate invitation with status tracking.',
        icon: '📨',
        status: 'pending',
        dependencies: ['Card', 'Badge', 'Button'],
        filePath: 'components/employer/InvitationCard.tsx',
      },
      {
        id: 'job-post-form',
        name: 'JobPostForm',
        description: 'Multi-step job posting form with preview and AI suggestions.',
        icon: '📝',
        status: 'pending',
        dependencies: ['Input', 'Select', 'Textarea', 'Button'],
        filePath: 'components/employer/JobPostForm.tsx',
      },
      {
        id: 'hiring-metric',
        name: 'HiringMetric',
        description: 'Hiring analytics metric card with trend and comparison.',
        icon: '📊',
        status: 'pending',
        dependencies: ['StatCard'],
        filePath: 'components/employer/HiringMetric.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 15. GAMIFICATION
  // ──────────────────────────────────────────────
  {
    id: 'gamification',
    name: 'Gamification',
    icon: '🎮',
    description: 'Engagement components for XP, badges, streaks, and leaderboards.',
    components: [
      {
        id: 'xp-bar',
        name: 'XPBar',
        description: 'Experience points progress bar with level indicator.',
        icon: '⭐',
        status: 'pending',
        dependencies: ['Progress'],
        filePath: 'components/gamification/XPBar.tsx',
      },
      {
        id: 'achievement-badge',
        name: 'AchievementBadge',
        description: 'Earned achievement badge with name, description, and date.',
        icon: '🏅',
        status: 'pending',
        dependencies: ['Badge'],
        filePath: 'components/gamification/AchievementBadge.tsx',
      },
      {
        id: 'streak-counter',
        name: 'StreakCounter',
        description: 'Daily/weekly activity streak counter with fire icon.',
        icon: '🔥',
        status: 'pending',
        dependencies: [],
        filePath: 'components/gamification/StreakCounter.tsx',
      },
      {
        id: 'leaderboard',
        name: 'Leaderboard',
        description: 'Leaderboard table with ranks, avatars, and scores.',
        icon: '🏆',
        status: 'pending',
        dependencies: ['Avatar', 'Table'],
        filePath: 'components/gamification/Leaderboard.tsx',
      },
    ],
  },

  // ──────────────────────────────────────────────
  // 16. MESSAGING
  // ──────────────────────────────────────────────
  {
    id: 'messaging',
    name: 'Messaging',
    icon: '💌',
    description: 'Messaging components for conversations, threads, and notifications.',
    components: [
      {
        id: 'conversation-list',
        name: 'ConversationList',
        description: 'List of chat conversations with preview, unread count, and timestamp.',
        icon: '📋',
        status: 'pending',
        dependencies: ['Avatar', 'Badge'],
        filePath: 'components/messaging/ConversationList.tsx',
      },
      {
        id: 'message-bubble',
        name: 'MessageBubble',
        description: 'Message bubble with sender info, text, attachments, and read receipts.',
        icon: '💬',
        status: 'pending',
        dependencies: ['Avatar'],
        filePath: 'components/messaging/MessageBubble.tsx',
      },
      {
        id: 'message-input',
        name: 'MessageInput',
        description: 'Message composer with text input, attachment, emoji, and send.',
        icon: '⌨️',
        status: 'pending',
        dependencies: ['Button'],
        filePath: 'components/messaging/MessageInput.tsx',
      },
      {
        id: 'notification-item',
        name: 'NotificationItem',
        description: 'Notification item with icon, message, timestamp, and read state.',
        icon: '🔔',
        status: 'pending',
        dependencies: ['Avatar'],
        filePath: 'components/messaging/NotificationItem.tsx',
      },
    ],
  },
];

// Flatten all components for quick lookup
export const allComponents: (ComponentItem & { categoryId: string })[] =
  componentCategories.flatMap((cat) =>
    cat.components.map((comp) => ({ ...comp, categoryId: cat.id }))
  );

// Stats
export const totalComponents = allComponents.length;
export const totalCategories = componentCategories.length;
export const readyComponents = allComponents.filter((c) => c.status === 'ready').length;
export const pendingComponents = allComponents.filter((c) => c.status === 'pending').length;
